removed empty py files
facebookresearch/rl pull request #81
Opened 2022-04-20 00:40 UTC by Ephibbs

2022-04-20 00:42 UTC, Ephibbs commented
solves #67

2022-04-20 06:14 UTC, vmoens requested changes
Once the `__init__.py` is edited and the checks pass we're good to go.

2022-04-21 01:36 UTC, Ephibbs commented on torchrl/record/rendering.py
> -# Copyright (c) Meta Platforms, Inc. and affiliates.
Yes, I updated this in the latest commit.

2022-04-21 03:47 UTC, vmoens commented
LGTM thanks!

2022-04-21 03:48 UTC, vmoens approved these changes

2022-04-21 03:48 UTC, merged